---
# TODO: extract from the same apps definition instead
envoy_config:
  ports:
    - 443
    - 1234
  domains:
    - name: "media"
      address: 127.0.0.1
      port: 8096
      proto: http
    - name: "sudo"
      address: 192.168.1.12
      port: 8080
      proto: http
    - name: "expenses"
      address: node4
      port: 8080
      proto: http
    - name: "homeassistant"
      address: node3
      port: 8123
      proto: http
    - name: "grafana"
      address: node4
      port: 18443
      proto: http

dns_domains:
  - name: "media.dcaro.es"
  - name: "sudo.dcaro.es"
  - name: "homeassistant.dcaro.es"
  - name: "expenses.dcaro.es"
  - name: "znc.dcaro.es"
  - name: "ssh.dcaro.es"
  - name: "grafana.dcaro.es"
  - name: "polaris.dcaro.es"
    ip: 68.183.240.105

dhcpd_config:
    gateway: 192.168.1.1
    dns-servers:
      - "{{ ansible_host }}"
      # we use the above for recursive resolving
      #- 1.1.1.1
      #- 8.8.8.8
    static-hosts:
      - name: magnum
        ip4: 192.168.1.102
        mac: 28:7f:cf:95:c4:af
      - name: vulcanus
        ip4: 192.168.1.101
        mac: c8:58:c0:ce:a4:dc

dns_config:
  forwarders:
    - 1.1.1.1
    - 8.8.8.8

remote_port: 32222
local_port: 22
