---
- name: "envoy-tunnel tasks"
  tags:
    - envoy-proxy
  block:
    - name: "Add envoy repo"
      yum_repository:
        name: "Tetrate GetEnvoy - Stable"
        baseurl: "https://rpm.dl.getenvoy.io/public/rpm/el/8/$basearch"
        enabled: true
        gpgkey: "https://rpm.dl.getenvoy.io/public/gpg.CF716AF503183491.key"
        gpgcheck: false
        sslverify: true
        sslcacert: "/etc/pki/tls/certs/ca-bundle.crt"
        metadata_expire: "300"
        description: "Envoy packages"

    - name: "Install packages"
      ansible.builtin.package:
        name: "getenvoy-envoy"
        state: present

    - name: "Add envoy service"
      ansible.builtin.copy:
        src: envoy.service
        dest: "/usr/lib/systemd/system/envoy.service"
      notify:
        - "Reload envoy"

    - name: "Add envoy proxy config"
      template:
        src: envoy.yaml.j2
        dest: "/etc/envoy.yaml"
      notify:
        - "Reload envoy"

    - name: "Make sure envoy is running"
      ansible.builtin.systemd:
        name: envoy
        state: started
        enabled: True

- name: "envoy-tunnel tasks"
  tags:
    - envoy-tunnel
  block:
    - name: "Make sure ssh dir exists"
      ansible.builtin.file:
        state: "directory"
        path: "/root/.ssh/"
        owner: root
        group: root
        mode: '700'

    - name: "Add ssh tunnel credentials"
      with_items:
        - "{{ secrets_repo_path }}/home_automation/envoy-tunnel/id_rsa"
        - "{{ secrets_repo_path }}/home_automation/envoy-tunnel/id_rsa.pub"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/root/.ssh/"
        owner: root
        group: root
        mode: '400'
      notify:
        - "Reload envoy-tunnel"

    - name: "Add ssh tunnel service"
      ansible.builtin.copy:
        src: envoy-tunnel.service
        dest: "/usr/lib/systemd/system/envoy-tunnel.service"
      notify:
        - "Reload envoy-tunnel"

    - name: "Make sure envoy-tunnel is running"
      ansible.builtin.systemd:
        name: envoy-tunnel
        state: started
        enabled: True
