---
- name: "git-client tasks"
  tags:
    - "git-client"
  block:
    - name: Check if rebooted since the last check
      ansible.builtin.stat:
        path: "/tmp/ansible.git-client-done"
      register: setup_done

    - name: Create the git-client-done file
      ansible.builtin.file:
        path: "/tmp/ansible.git-client-done"
        state: touch
      when: not setup_done.stat.exists

    - name: "Install packages"
      ansible.builtin.package:
        name:
          - vim
          - git
      when:
        - not setup_done.stat.exists

    - name: "Add gitexcludes"
      ansible.builtin.copy:
        src: "{{ item.1 }}"
        dest: "~{{ item.0.name }}/.{{ item.1 }}"
      loop: "{{ users|zip(files * 10) }}"
      vars:
        files:
          - gitexcludes

    - name: "Add gitconfigs"
      ansible.builtin.template:
        src: "{{ item.1 }}.j2"
        dest: "~{{ item.0.name }}/.{{ item.1 }}"
      loop: "{{ users|zip(files * 10) }}"
      vars:
        files:
          - gitconfig
