---
- name: "Disable firewalld"
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: False

- name: "Add jellyfin service"
  ansible.builtin.copy:
    src: jellyfin.service
    dest: "/usr/lib/systemd/system/jellyfin.service"

- name: "Make sure it's running"
  ansible.builtin.systemd:
    name: jellyfin
    state: started
    enabled: True
