---
- name: "DNS tasks"
  tags:
    - "dns"
  block:
  - name: "Install packages"
    ansible.builtin.package:
      name: "{{ 'bind' if ansible_facts['distribution'] != 'Debian' else 'bind9' }}"
      state: present

  - name: "Add bind config - non Debian named.conf"
    template:
      src: named.conf.j2
      dest: "/etc/named.conf" 
    notify:
      - "Reload named"
    when:
      - ansible_facts['distribution'] != 'Debian'

  - name: "Add bind config - Debian"
    template:
      src: "{{ item.template }}"
      dest: "{{ item.dest }}" 
    with_items:
      - template: named.conf.local.j2
        dest: "/etc/bind/named.conf.local" 
      - template: named.conf.options.j2
        dest: "/etc/bind/named.conf.options" 
    notify:
      - "Reload named"
    when:
      - ansible_facts['distribution'] == 'Debian'

  - name: "Add dcaro.es zone config"
    template:
      src: dcaro.es.zone.j2
      dest: "{{ '/etc/named/dcaro.es.zone' if ansible_facts['distribution'] != 'Debian' else '/etc/bind/dcaro.es.zone' }}" 
    notify:
      - "Reload named"

  - name: "Make sure it's running"
    ansible.builtin.systemd:
      name: "named"
      state: started
      enabled: True

  - name: "Add dns service to firewalld"
    ansible.posix.firewalld:
      service: dns
      permanent: true
      state: enabled

