---
- name: Install a container runtime (podman)
  become: true
  ansible.builtin.apt:
    name:
      - podman
      - lvm2
      - rbd-nbd
      - btrfs-progs
    state: present

- name: Install cephadm
  become: true
  copy:
    src: cephadm
    dest: /usr/local/bin/cephadm
    owner: root
    group: root
    mode: 0750
