---
- ansible.builtin.apt:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Debian"
  with_items:
    - vim
    - byobu
    - mosh
    - prometheus-node-exporter
    - python3-firewall
    - firewalld

- ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_hostname != 'vulcanus' 

- ansible.builtin.package:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Fedora"
  with_items:
    - vim
    - mosh
    - byobu
    - golang-github-prometheus-node-exporter


- name: "Add vimrc - Debian"
  ansible.builtin.copy:
      src: vimrc
      dest: "/etc/vim/vimrc.local"
  when:
    - ansible_facts['distribution'] == "Debian"

- name: "Add vimrc - other"
  ansible.builtin.copy:
      src: vimrc
      dest: "/etc/vimrc.local"
  when:
    - ansible_facts['distribution'] != "Debian"
