---
- ansible.builtin.apt:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Debian"
  with_items:
    - vim
    - mosh
    - prometheus-node-exporter
    - python3-firewall

- ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  when:
    - ansible_facts['distribution'] == "Debian"

- ansible.builtin.package:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Fedora"
  with_items:
    - vim
    - mosh
    - byobu
    - golang-github-prometheus-node-exporter
