---
- name: Check if rebooted since the last check
  ansible.builtin.stat:
    path: "/tmp/ansible.basic-server-done"
  register: setup_done

- name: Create the basic-server-done file
  ansible.builtin.file:
    path: "/tmp/ansible.basic-server-done"
    state: touch
  when: not setup_done.stat.exists

- ansible.builtin.apt:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Debian"
    - not setup_done.stat.exists
  with_items:
    - vim
    - byobu
    - mosh
    - prometheus-node-exporter
    - python3-firewall
    - firewalld
    - strace
    - htop

- ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
    immediate: true
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_hostname != 'vulcanus'

- ansible.builtin.package:
    name: "{{ item }}"
  when:
    - ansible_facts['distribution'] == "Fedora"
    - not setup_done.stat.exists
  with_items:
    - vim
    - mosh
    - byobu
    - node-exporter

- name: "Add vimrc - Debian"
  ansible.builtin.copy:
    src: vimrc
    dest: "/etc/vim/vimrc.local"
  when:
    - ansible_facts['distribution'] == "Debian"

- name: "Add vimrc - other"
  ansible.builtin.copy:
    src: vimrc
    dest: "/etc/vimrc.local"
  when:
    - ansible_facts['distribution'] != "Debian"
