---
- name: setup users
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
  loop: "{{ users }}"

- name: setup ssh keys
  become: true
  ansible.posix.authorized_key:
    state: present
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
  loop: "{{ users }}"

- name: enable ssh
  become: true
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: allow passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/010_{{ item.name }}-nopasswd"
    owner: root
    group: root
    mode: '0440'
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
  loop: "{{ users }}"
