---
- name: "Install packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - ansible-collection-ansible-netcommon
    - ansible-collection-ansible-utils
    - ansible-collection-containers-podman
    - ansible-collection-community-general
    - ansible-collection-ansible-posix

- name: "Add ansible-runner script"
  ansible.builtin.copy:
    src: ansible-runner.sh
    dest: "/usr/local/bin/ansible-runner.sh"
    mode: "0555"

- name: "Add ansible-runner service"
  ansible.builtin.copy:
    src: ansible-runner.service
    dest: "/usr/lib/systemd/system/ansible-runner.service"

- name: "Make sure it's running"
  ansible.builtin.systemd:
    name: ansible-runner
    state: started
    enabled: True
