---
- name: "create app {{ current_app.name }}"
  tags:
    - "{{ current_app.name }}"
  block:
    - name: "Create rbd (nbd) volumes for app '{{ current_app.name }}'"
      include_tasks: create_rbd_volume.yaml
      loop: "{{ current_app.nbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.nbd_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Mount nbd volumes for app '{{ current_app.name }}'"
      include_tasks: mount_nbd_volume.yaml
      loop: "{{ current_app.nbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.nbd_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Populate nbd volumes for app '{{ current_app.name }}' "
      include_tasks: populate_nbd_volume.yaml
      loop: "{{ current_app.nbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.nbd_volumes is defined
        - current_app.nbd_volumes.src is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Create rbd volumes for app '{{ current_app.name }}'"
      include_tasks: create_rbd_volume.yaml
      loop: "{{ current_app.rbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.rbd_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Mount rbd volumes for app '{{ current_app.name }}'"
      include_tasks: mount_rbd_volume.yaml
      loop: "{{ current_app.rbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.rbd_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Populate rbd volumes for app '{{ current_app.name }}' "
      include_tasks: populate_rbd_volume.yaml
      loop: "{{ current_app.rbd_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.rbd_volumes is defined
        - current_app.rbd_volumes.src is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Mount nfs volumes for app '{{ current_app.name }}'"
      include_tasks: mount_nfs_volume.yaml
      loop: "{{ current_app.nfs_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.nfs_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Create file volumes for app '{{ current_app.name }}'"
      include_tasks: create_file_volume.yaml
      loop: "{{ current_app.file_volumes }}"
      loop_control:
        loop_var: current_volume
      when:
        - current_app.file_volumes is defined
        - only_apps is not defined or current_app.name in only_apps

    - name: "Start app '{{ current_app.name }}'"
      tags:
        - podman
        - container
      when:
        - only_apps is not defined or current_app.name in only_apps
      containers.podman.podman_container:
        name: "{{ current_app.name }}"
        image: "{{ current_app.image }}"
        state: started
        privileged: "{{ current_app.privileged | default(false) }}"
        ports: "{{ current_app.ports | default([]) }}"
        command: "{{ current_app.command | default(omit) }}"
        restart_policy: "always"
        entrypoint: "{{ current_app.entrypoint | default(omit) }}"
        workdir: "{{ current_app.workdir | default(omit) }}"
        env: "{{ current_app.env | default({}) }}"
        # file volumes at the end so they are mounted inside the other ones if
        # needed
        volumes: >-
          {{
            (
            current_app.nfs_volumes | default([])
            + current_app.nbd_volumes | default([])
            + current_app.rbd_volumes | default([])
            + current_app.simple_volumes | default([])
            + current_app.file_volumes | default([])
            ) | to_podman_volumes
          }}
        device: "{{ current_app.device | default(omit) }}"
