---
- name: "Create app '{{ current_app.name }}' rbd volumes"
  include_tasks: create_rbd_volume.yml
  loop: "{{ current_app.rbd_volumes }}"
  loop_control:
    loop_var: current_volume
  when: current_app.rbd_volumes is defined

- name: "Mount rbd volumes for app '{{ current_app.name }}'"
  include_tasks: mount_rbd_volume.yml
  loop: "{{ current_app.rbd_volumes }}"
  loop_control:
    loop_var: current_volume
  when: current_app.rbd_volumes is defined

- name: "Populate rbd volumes for app '{{ current_app.name }}' "
  include_tasks: populate_rbd_volume.yml
  loop: "{{ current_app.rbd_volumes }}"
  loop_control:
    loop_var: current_volume
  when: current_app.rbd_volumes is defined

- name: "Mount nfs volumes for app '{{ current_app.name }}'"
  include_tasks: mount_nfs_volume.yml
  loop: "{{ current_app.nfs_volumes }}"
  loop_control:
    loop_var: current_volume
  when: current_app.nfs_volumes is defined

- name: "Start app '{{ current_app.name }}'"
  containers.podman.podman_container:
    name: "{{ current_app.name }}"
    image: "{{ current_app.image }}"
    state: started
    privileged: "{{ current_app.privileged | default(false) }}"
    ports: "{{ current_app.ports }}"
    volumes: "{{ (current_app.nfs_volumes + current_app.rbd_volumes) | to_podman_volumes }}"
    device: "{{ current_app.device | default('') }}"
