---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - btrfs-progs
    # current debian 11 kernel for raspberry has no rbd module in it, so we use
    # the nbd client
    - rbd-nbd
  when: apps is defined

- name: Create apps
  include_tasks: create_app.yml
  loop: "{{ apps }}"
  loop_control:
    loop_var: current_app
  when: apps is defined
