---
- name: Install packages
  tags:
    - install-packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - btrfs-progs
    # current debian 11 kernel for raspberry has no rbd module in it, so we use
    # the nbd client
    - rbd-nbd
  when: apps is defined

- name: Got apps
  tags:
    - create-apps
  ansible.builtin.debug:
    msg: "Apps: {{ apps }}"
  when: apps is defined

- name: Create apps
  tags:
    - create-apps
  include_tasks: create_app.yaml
  loop: "{{ apps }}"
  loop_control:
    loop_var: current_app
  when: apps is defined
