---
- name: "Create mountpoint"
  ansible.builtin.file:
    path: "/mnt/{{ current_volume.name }}"
    state: "directory"

- name: "Mount volume '{{ current_volume.name }}'"
  ansible.posix.mount:
    path: "/mnt/{{ current_volume.name }}"
    opts: noauto,rw
    src: "{{ current_volume.src }}"
    fstype: nfs
    state: mounted
