---
- name: Add the cluster hosts to the hosts file
  hosts: 127.0.0.1
  become: true
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - set-hosts
