---
# TODO: find a way to reload the podman container
#- name: Reload envoy
#  ansible.builtin.systemd:
#    daemon_reload: true
#    name: envoy
#    state: restarted

- name: Reload envoy-tunnel
  ansible.builtin.systemd:
    daemon_reload: true
    name: envoy-tunnel
    state: restarted

- name: Reload certbot
  ansible.builtin.systemd:
    daemon_reload: true
    name: certbot
    state: restarted
