---
- name: "ssh-bastion tasks"
  tags:
    - ssh-bastion
  when:
    - ssh_bastion is defined
  block:
    - name: "Make sure ssh dir exists"
      ansible.builtin.file:
        state: "directory"
        path: "/root/.ssh/"
        owner: root
        group: root
        mode: '700'

    - name: "Add ssh bastion credentials"
      with_items:
        - "{{ secrets_repo_path }}/home_automation/envoy-tunnel/id_rsa"
        - "{{ secrets_repo_path }}/home_automation/envoy-tunnel/id_rsa.pub"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/root/.ssh/"
        owner: root
        group: root
        mode: '400'
      notify:
        - "Reload ssh-bastion"

    - name: "Add polaris public key"
      ansible.builtin.known_hosts:
        name: "polaris.dcaro.es"
        key: "polaris.dcaro.es ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmOOnlfMDmkcCwfn/n3C1H4gYRTXHo4VjvdmVPAQo/bquemE5tOAuD8KjwJ/3OGDp+RZO0BiUEKiiA1WsK6dmzYpF4HkixzWTs3IUrRUj4OJCMnG5gtnLJi3B7OnTVj3Zt92buzjckHMJCwtgmekRqpAngE5hYbOpHM/uoDJhbejOCENrW/4ABrwgqr4fW7XZ+iwem8oJhsUZ5l0dB4kUxtOdmYuU9ApYuxMhrCQkjp+sCbs75cZqo5EHVB4r8eSv5YtfvSpMtafCbJONLKRLrNY0uyYa8lF6AWvZ478BRGtyySwWGCKlmaNTd70hA9Vq+wbA+q9XfDIyMQaLrEIvB51xYroIa1tjd0ahFGwbSo8mXx0cSGPWcm1zAmZgjbRxWdGQ9ILjjS6dM5cOQtdeZZJhSsl/hVhP4UDugRsw27jevQmOOjlsN2Ageppk5zz9c2Tue+c7+QW+DbMyjQoQSWlqu+jmjhTCnezEPrYWplhl14/pKBtl6ebK5Rf2YDpU="

    - name: "Add ssh bastion service"
      ansible.builtin.template:
        src: ssh-bastion.service.j2
        dest: "/usr/lib/systemd/system/ssh-bastion.service"
      notify:
        - "Reload ssh-bastion"

    - name: "Make sure ssh-bastion is running"
      ansible.builtin.systemd:
        name: ssh-bastion
        state: started
        enabled: True
