---
- name: Flush iptables before changing to iptables-legacy
  become: true
  iptables:
    flush: true
  changed_when: false   # iptables flush always returns changed

- name: Changing to iptables-legacy
  become: true
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy
  notify: Reboot PI

- name: Changing to ip6tables-legacy
  become: true
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy
  notify: Reboot PI
