---
- name: setup users (raspberry)
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
    append: true
  loop: "{{ users }}"
  when: >-
    'raspberries' in group_names

- name: setup users (other)
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: adm,dialout,cdrom,audio,video,games,users,input
    append: true
  loop: "{{ users }}"
  when: >-
    'raspberries' not in group_names

- name: setup ssh keys
  become: true
  ansible.posix.authorized_key:
    state: present
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ users | subelements('ssh_public_keys')  }}"

- name: enable ssh (raspberry)
  become: true
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started
  when: >-
    'raspberries' in group_names

- name: enable ssh (other)
  become: true
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: started
  when: >-
    'raspberries' in group_names

- name: allow passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/010_{{ item.name }}-nopasswd"
    owner: root
    group: root
    mode: "0440"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
  loop: "{{ users }}"
