---
- name: Install basic common packages I want everywhere
  hosts: all
  become: true
  tasks:
    - ansible.builtin.apt:
        name: "{{ item }}"
      when:
        - ansible_facts['distribution'] == "Debian"
      with_items:
        - vim
        - mosh
        - byobu

    - ansible.builtin.apt:
        name: "{{ item }}"
      when:
        - ansible_facts['distribution'] == "Fedora"
      with_items:
        - vim
        - mosh
        - byobu

