---
- name: install k3s users and common tasks
  hosts: k3servers,k3agents
  vars:
    ansible_ssh_user: kubeadmin
  roles:
    - k3s-common

- name: install first k3s server node
  hosts: node1
  vars:
    ansible_ssh_user: kubeadmin
  roles:
    - k3s-init-server

- name: install the rest of the k3s server nodes
  hosts: k3servers,!node1
  vars:
    ansible_ssh_user: kubeadmin
  roles:
    - k3s-server

- name: install k3s agents
  hosts: k3agents
  vars:
    ansible_ssh_user: kubeadmin
  roles:
    - k3s-agent
