---
- name: "fail2ban tasks"
  tags:
    - "fail2ban"
  block:
    - name: Check if rebooted since the last check
      ansible.builtin.stat:
        path: "/tmp/ansible.fail2ban-done"
      register: setup_done

    - name: Create the fail2ban-done file
      ansible.builtin.file:
        path: "/tmp/ansible.fail2ban-done"
        state: touch
      when: not setup_done.stat.exists

    - name: "Install fail2ban packages"
      ansible.builtin.package:
        name: "{{ item }}"
      with_items:
        - fail2ban
      when: not setup_done.stat.exists

    - name: "Add sshd fail2ban jail config"
      ansible.builtin.copy:
        src: "00-sshd.conf"
        dest: "/etc/fail2ban/jail.d/00-sshd.conf"
      notify:
        - "Reload fail2ban"

    - name: "Make sure it's running"
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: True
