---
- name: add known nodes to the hosts file
  become: true
  ansible.builtin.lineinfile:
    line: "{{ hostvars[host]['ansible_host'] }} {{ host }}"
    path: "/etc/hosts"
  loop: "{{ groups['all'] }}"
  loop_control:
    loop_var: host
