---
- name: "DHCP tasks"
  tags:
    - "dhcp"
  block:
    - name: "Install packages"
      ansible.builtin.package:
        name: "{{ 'dhcp-server' if ansible_facts['distribution'] != 'Debian' else 'isc-dhcp-server' }}"
        state: present

    - name: "Add dhcp config"
      template:
        src: dhcpd.conf.j2
        dest: "/etc/dhcp/dhcpd.conf"
      notify:
        - "Reload dhcpd"

    - name: "Setup interface config - Debian"
      ansible.builtin.copy:
        src: "isc-dhcp-server"
        dest: "/etc/default/isc-dhcp-server"
      when:
        - ansible_facts['distribution'] == 'Debian'

    - name: "Make sure it's running"
      ansible.builtin.systemd:
        name: "{{ 'dhcp' if ansible_facts['distribution'] != 'Debian' else 'isc-dhcp-server' }}"
        state: started
        enabled: True

