---
- name: Setup the NFS exports on the storage server
  hosts: eopsin
  become: true
  pre_tasks:
    - name: "load ip-updater secrets"
      include_vars:
        file: "{{ secrets_repo_path }}/ovh_creds.yml"
        name: ovh_creds
      no_log: true
      tags:
        - ip-updater
  roles:
    - role: nfs-server
      tags:
        - nfs
