---
- name: Setup the NFS exports on the storage server
  hosts: eopsin
  become: true
  roles:
    - role: nfs-server
      tags:
        - nfs
    - role: jellyfin
      tags:
        - jellyfin
        - media
    - role: envoy-proxy
      tags:
        - envoy
        - proxy
    - role: fail2ban
      tags:
        - fail2ban
    - role: ansible-runner
      tags:
        - ansible-runner
    - role: dhcp-server
      tags:
        - dhcp-server
        - dhcp
    - role: dns-server
      tags:
        - dns-server
        - dns
