---
- name: Setup the NFS exports on the storage server
  hosts: eopsin
  become: true
  roles:
    - nfs-server
    - jellyfin
    - envoy-proxy
    - fail2ban
    - ansible-runner
    - dhcp-server
