---
- name: Setup personal servers
  hosts: personal
  become: true
  roles:
    - role: set-hosts
      tags: set-hosts
    - role: bash-userconfig
      tags: bash-userconfig
    - role: atuin
      tags: atuin
    - role: coding
      tags: coding
    # - role: dotfiles
    #   tags: dotfiles
