---
- name: Setup personal servers
  hosts: personal
  become: true
  roles:
    - role: bash-userconfig
      tags: bash-userconfig
    - role: atuin
      tags: atuin
    - role: coding
      tags: coding
    - role: dotfiles
      tags: dotfiles
