---
- name: Setup all applications in the server
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - name: "load expenses secrets"
      include_vars:
        file: "{{ secrets_repo_path }}/home_automation/expenses/db_config.yaml"
        name: expenses_db_config
      no_log: true

    - name: "load prometheus secrets"
      include_vars:
        file: "{{ secrets_repo_path }}/home_automation/prometheus_creds.yml"
        name: prometheus_creds_config
      no_log: true
      tags:
        - prometheus

    - name: "load atuin secrets"
      include_vars:
        file: "{{ secrets_repo_path }}/home_automation/atuin_creds.yml"
        name: atuin_creds_config
      no_log: true
      tags:
        - atuin
  roles:
    - app-server
