---
- name: "Setup coding environment"
  tags:
    - "coding"
  block:
    - name: Check if rebooted since the last check
      ansible.builtin.stat:
        path: "/tmp/ansible.coding-done"
      register: setup_done

    - name: Create the coding-done file
      ansible.builtin.file:
        path: "/tmp/ansible.coding-done"
        state: touch
      when: not setup_done.stat.exists

    - name: "Custom repos"
      ansible.builtin.yum_repository:
        name: "{{ repo.name }}"
        description: "{{ repo.description }}"
        baseurl: "{{ repo.baseurl }}"
        gpgkey: "{{ repo.gpgkey }}"
        enabled: true
      loop: "{{ repos }}"
      loop_control:
        loop_var: "repo"

    - name: "Install dnf packages"
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - code
        - golang
        - gh
        - python3-virtualenv
        - gvim
        - google-chrome
        - cmake
        - gcc
        - podman
        - podman-docker
        - rvm
        - protonvpn
      when:
        - not setup_done.stat.exists

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | sudo -u {{ item }} bash
      args:
        creates: "/home/{{ item }}/.nvm/nvm.sh"
      loop:
        - dinika
        - dcaro

    - name: "Install flatpack packages"
      community.general.flatpak:
        state: present
        name: "{{ item }}"
      loop:
        - io.podman_desktop.PodmanDesktop
        - com.github.iwalton3.jellyfin-media-player
      when:
        - not setup_done.stat.exists
