---
- name: "Setup coding environment"
  tags:
    - "coding"
  block:
    - name: "Custom repos"
      ansible.builtin.yum_repository:
        name: "{{ repo.name }}"
        description: "{{ repo.name }}"
        baseurl: "{{ repo.baseurl }}"
        gpgkey: "{{ repo.gpgkey }}"
      loop: "{{ repos }}"
      loop_control:
        loop_var: "repo"

    - name: "Install dnf packages"
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - code
        - golang
        - gh
        - python3-virtualenv
        - gvim
        - google-chrome
        - cmake
        - gcc
        - podman
        - podman-docker
        - rvm

    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | sudo -u {{ item }} bash
      args:
        creates: "/home/{{ item }}/.nvm/nvm.sh"
      loop:
        - dinika
        - dcaro

    - name: "Install flatpack packages"
      community.general.flatpak:
        state: present
        name: "{{ item }}"
      loop:
        - io.podman_desktop.PodmanDesktop
        - com.github.iwalton3.jellyfin-media-player