---
exports:
  - name: /data
    options: rw,sync,no_root_squash
    nodes: cluster
  - name: /data
    options: ro,sync,no_root_squash
    nodes: 192.168.1.0/24

# TODO: extract from the same apps definition instead
envoy_config:
  base_port: 443
  domains:
    - name: "media"
      address: 127.0.0.1
      port: 8096
      proto: http
    - name: "sudo"
      address: 192.168.1.12
      port: 8080
      proto: http
    - name: "expenses"
      address: node4
      port: 8080
      proto: http
    - name: "homeassistant"
      address: node3
      port: 8123
      proto: http
    - name: "grafana"
      address: node4
      port: 18443
      proto: http

# TODO: dynamic host entries in the dns
# TODO: find an automated way to get the external ip
dns_domains:
  - name: "media.dcaro.es"
  - name: "sudo.dcaro.es"
  - name: "homeassistant.dcaro.es"
  - name: "expenses.dcaro.es"
  - name: "znc.dcaro.es"
  - name: "ssh.dcaro.es"

dhcpd_config:
    static-hosts: []
