---
desired_ipaddress: 192.168.1.24
apps:
  - name: "grafana"
    image: "docker.io/grafana/grafana:latest"
    rbd_volumes:
      - name: "grafana_data01"
        size: "1GB"
        dest: "/var/lib/grafana"
        mount_mode: "rw"
      - name: "grafana_logs01"
        size: "50MB"
        dest: "/var/log/grafana"
        mount_mode: "rw"
    file_volumes:
      - name: "Grafana config"
        host_src: "/mnt/grafana.ini"
        dest: "/etc/grafana/grafana.ini"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/grafana.ini"
    simple_volumes:
      - name: "Timezone"
        host_src: "/etc/timezone"
        dest: "/etc/timezone"
        mount_mode: "ro"
      - name: "Localtime"
        host_src: "/etc/localtime"
        dest: "/etc/localtime"
        mount_mode: "ro"
    nbd_volumes: []
    ports:
      - "18443:18443/tcp"
  - name: "prometheus"
    image: "docker.io/prom/prometheus:latest"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.size=15GB"
    nbd_volumes: []
    rbd_volumes:
      - name: "prometheus_data01"
        size: "10GB"
        dest: "/prometheus"
        mount_mode: "rw"
        contents: "{{ secrets_repo_path }}/prometheus"
    nfs_volumes: []
    file_volumes:
      - name: "Prometheus config"
        host_src: "/mnt/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        file_mode: "644"
        mount_mode: "ro"
        template: "prometheus.yaml.j2"
      - name: "Node expotrer ssl cert"
        host_src: "/mnt/node-exporter.crt"
        dest: "/etc/prometheus/node-exporter.crt"
        file_mode: "640"
        mount_mode: "ro"
        local_src: "node-exporter.crt"
    simple_volumes:
      - name: "Timezone"
        host_src: "/etc/timezone"
        dest: "/etc/timezone"
        mount_mode: "ro"
      - name: "Localtime"
        host_src: "/etc/localtime"
        dest: "/etc/localtime"
        mount_mode: "ro"
    ports:
      - "9090:9090/tcp"
  - name: "expenses_db"
    image: "docker.io/arm64v8/mariadb:latest"
    rbd_volumes:
      - name: "expenses_db"
        size: "1GB"
        dest: "/var/lib/mysql"
        mount_mode: "rw"
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    ports:
      - "3306:3306/tcp"

  - name: "expenses_postgres"
    image: "docker.io/postgres:latest"
    rbd_volumes:
      - name: "expenses_postgres"
        size: "1GB"
        dest: "/var/lib/postgresql/data"
        mount_mode: "rw"
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    ports:
      - "5432:5432/tcp"
    env:
      POSTGRES_USER: "{{expenses_db_config.DB_USERNAME}}"
      POSTGRES_PASSWORD: "{{expenses_db_config.DB_PASSWORD}}"
      POSTGRES_DB: expenses

  - name: "expenses_app"
    image: "quay.io/farting_lizards/expenses:20240428"
    rbd_volumes: []
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    env:
      DB_URL: "postgresql://{{expenses_db_config.DB_USERNAME}}:{{expenses_db_config.DB_PASSWORD}}@{{expenses_db_config.DB_HOST}}:/expenses"
    ports:
      - "8081:8000/tcp"

  - name: "expenses_nginx"
    image: "docker.io/library/nginx"
    rbd_volumes: []
    nfs_volumes: []
    file_volumes:
      - name: "Nginx htpasswd"
        host_src: "/mnt/expenes_auth"
        dest: "/etc/nginx/.htpasswd"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/home_automation/expenses/expenses_auth"
      - name: "Nginx config"
        host_src: "/mnt/expenses_nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/home_automation/expenses/expenses_nginx.conf"
    simple_volumes: []
    nbd_volumes: []
    ports:
      - "8080:80/tcp"

  - name: "whatismyip_app"
    image: "quay.io/farting_lizards/iphinter:latest"
    rbd_volumes: []
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    env: {}
    ports:
      - "8082:7777/tcp"

ssh_bastion:
  local_port: 22
  remote_port: 32204
