---
desired_ipaddress: 192.168.1.24
apps:
  - name: "grafana"
    image: "docker.io/grafana/grafana:latest"
    rbd_volumes:
      - name: "grafana_data01"
        size: "1GB"
        dest: "/var/lib/grafana"
        mount_mode: "rw"
      - name: "grafana_logs01"
        size: "50MB"
        dest: "/var/log/grafana"
        mount_mode: "rw"
    file_volumes:
      - name: "Grafana config"
        host_src: "/mnt/grafana.ini"
        dest: "/etc/grafana/grafana.ini"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/grafana.ini"
    simple_volumes:
      - name: "Timezone"
        host_src: "/etc/timezone"
        dest: "/etc/timezone"
        mount_mode: "ro"
      - name: "Localtime"
        host_src: "/etc/localtime"
        dest: "/etc/localtime"
        mount_mode: "ro"
    nbd_volumes: []
    ports:
      - "18443:18443/tcp"
  - name: "prometheus"
    image: "docker.io/prom/prometheus:latest"
    nbd_volumes: []
    rbd_volumes:
      - name: "prometheus_data01"
        size: "10GB"
        dest: "/prometheus"
        mount_mode: "rw"
        contents: "{{ secrets_repo_path }}/prometheus"
    nfs_volumes: []
    file_volumes:
      - name: "Prometheus config"
        host_src: "/mnt/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        file_mode: "644"
        mount_mode: "ro"
        template: "prometheus.yml.j2"
    simple_volumes:
      - name: "Timezone"
        host_src: "/etc/timezone"
        dest: "/etc/timezone"
        mount_mode: "ro"
      - name: "Localtime"
        host_src: "/etc/localtime"
        dest: "/etc/localtime"
        mount_mode: "ro"
    ports:
      - "9090:9090/tcp"
  - name: "expenses_db"
    image: "docker.io/arm64v8/mariadb:latest"
    rbd_volumes:
      - name: "expenses_db"
        size: "1GB"
        dest: "/var/lib/mysql"
        mount_mode: "rw"
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    ports:
      - "3306:3306/tcp"
  - name: "expenses_app"
    image: "quay.io/farting_lizards/expenses:latest"
    rbd_volumes: []
    nfs_volumes: []
    file_volumes: []
    simple_volumes: []
    nbd_volumes: []
    env:
      DB_PASSWORD: "{{expenses_db_config.DB_PASSWORD}}"
      DB_USERNAME: "{{expenses_db_config.DB_USERNAME}}"
      DB_HOST: "{{expenses_db_config.DB_HOST}}"
    ports:
      - "8081:8080/tcp"
  - name: "expenses_nginx"
    image: "docker.io/library/nginx"
    rbd_volumes: []
    nfs_volumes: []
    file_volumes:
      - name: "Nginx htpasswd"
        host_src: "/mnt/expenes_auth"
        dest: "/etc/nginx/.htpasswd"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/home_automation/expenses/expenses_auth"
      - name: "Nginx config"
        host_src: "/mnt/expenses_nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        file_mode: "644"
        mount_mode: "ro"
        local_src: "{{ secrets_repo_path }}/home_automation/expenses/expenses_nginx.conf"
    simple_volumes: []
    nbd_volumes: []
    ports:
      - "8080:80/tcp"
