---
- name: install docker.io
  become: true
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: enable and start docker
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: add our users to the docker group
  become: true
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups: docker
    append: true
  loop: "{{ users }}"
