---
- name: Add cephadm root ssh key
  become: true
  ansible.posix.authorized_key:
    state: present
    user: root
    key: "{{ hostvars[groups['cluster'][0]].cephadm_ssh_key_encoded.content | b64decode | trim }}"

- name: Add node to ceph orch
  become: true
  delegate_to: "{{ groups['cluster'][0] }}"
  shell:
    cmd: "cephadm --image={{ cephadm_image }} shell -- ceph orch host add {{ inventory_hostname }} {{ ansible_host }}"
